language: python
python:
    - "3.4"
    - "3.5"
    - "3.6"
install:
    - pip install coverage
before_script: 
    - git clone https://github.com/Araksya-Hambaryan/ITC-9.git
    - ls
script:
    - python json.py
after_script: coverage report
