language: python
python:
    - "3.4"
    - "3.5"
    - "3.6"
install:
    - pip install coverage
before_script: cd ./Arman_Avdalyan/Homeworks/Python/1_11.06/
script:
    - python json.py
after_script: coverage report
